
CREATE DATABASE CICLOGREEN
GO

USE CICLOGREEN
GO


CREATE TABLE CIUDADES(
	
	ID INT NOT NULL IDENTITY(1,1),
	Orografia VARCHAR (20) NOT NULL,
	Km_Carril_Bici SMALLINT NOT NULL,
	Num_hab INT NOT NULL,
	Extensión INT NOT NULL,
	
	CONSTRAINT PK_CIUDADES PRIMARY KEY (ID) 

)
GO



CREATE TABLE ESTACIONAMIENTOS(

	ID INT NOT NULL IDENTITY (1,1),
	Zona SMALLINT NOT NULL,
	ID_Ciudad INT NOT NULL,

	CONSTRAINT PK_ESTACIONAMIENTOS PRIMARY KEY (ID),
	CONSTRAINT FK_ESTACIONAMIENTOS_Ciudades FOREIGN KEY (ID_Ciudad) REFERENCES CIUDADES (ID) ON DELETE NO ACTION ON UPDATE CASCADE,

)
GO



CREATE TABLE TECNICOS(

	ID INT NOT NULL IDENTITY (1,1),
	Especialidad VARCHAR(25) NOT NULL,
	Nombre VARCHAR (20) NOT NULL,
	Apellidos VARCHAR (30) NOT NULL,

	CONSTRAINT PK_TECNICOS PRIMARY KEY (ID)

)
GO



CREATE TABLE CLIENTES(

	ID INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR (20) NOT NULL,
	Apellidos VARCHAR (30) NOT NULL,
	Num_tlf CHAR (9) NOT NULL,
	MetodoPago VARCHAR(15) NOT NULL,
	
	CONSTRAINT PK_CLIENTES PRIMARY KEY (ID), 
	CONSTRAINT CK_Num_tlf_CLIENTES CHECK (Num_tlf LIKE '[0-9]''[0-9]''[0-9]''[0-9]''[0-9]''[0-9]''[0-9]''[0-9]''[0-9]')

)
GO



CREATE TABLE BICICLETAS(

	ID INT NOT NULL IDENTITY(1,1),
	Modelo VARCHAR (20) NOT NULL,
	Marca VARCHAR (20) NULL,
	Electrica CHAR(2) NOT NULL,
	Precio SMALLINT NOT NULL,

	CONSTRAINT PK_BICICLETAS PRIMARY KEY (ID)

)
GO




CREATE TABLE AVERIAS(

	ID INT NOT NULL IDENTITY (1,1),
	Descripción VARCHAR (200) NOT NULL,
	Fecha SMALLDATETIME NOT NULL,
	Hora TIME NOT NULL,
	ID_Bicicleta INT NOT NULL,
	ID_Cliente INT NOT NULL,
	ID_Tecnico INT NULL,
	Fecha_Reparacion SMALLDATETIME NULL,

	CONSTRAINT PK_AVERIAS PRIMARY KEY (ID),
	CONSTRAINT FK_AVERIAS_Bicicletas FOREIGN KEY (ID_Bicicleta) REFERENCES BICICLETAS (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_AVERIAS_Clientes FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_AVERIAS_Tecnicos FOREIGN KEY (ID_Tecnico) REFERENCES TECNICOS (ID) ON DELETE NO ACTION ON UPDATE CASCADE

)
GO



CREATE TABLE AVERIAS_BICICLETAS(

	ID_Bicicleta INT NOT NULL,
	ID_Averia INT NOT NULL,

	CONSTRAINT PK_AVERIAS_BICICLETAS PRIMARY KEY (ID_Bicicleta, ID_Averia),
	CONSTRAINT FK_AVERIAS_BICICLETAS_Bicicletas FOREIGN KEY (ID_Bicicleta) REFERENCES BICICLETAS (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_AVERIAS_BICICLETAS_Averias FOREIGN KEY (ID_Averia) REFERENCES AVERIAS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION

)
GO



CREATE TABLE 